Proyecto/urls.py
from django.contrib import admin
from django.urls import path
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home_view'),
    path('articulo/', views.articuloVista.as_view(), name='articulo_view'),
    path('cliente/', views.clienteVista.as_view(), name='cliente_view'),
    path('proveedor/', views.proveedorVista.as_view(), name='proveedor_view'),
    path('listaArticulos/', views.listaArticulosVista, name='listaArticulos_view'),
    path('datosArticulo/<int:articulo_id>', views.datosArticulo, name='datosArticulo_view'),
    path('compra/', views.compraVistaAlternativa, name="compraVista_view"),
    path('almacen/', views.almacenVista.as_view(), name="almacenVista_view"),
    path('inventario/', views.inventarioVista.as_view(), name='inventarioVista_view'),
    path('venta/', views.ventaVista, name='venta_view'),
    path('cargarAlmacenes/', views.cargarAlmacenes, name='cargarAlmacenes_funcion'),
    path('cantidadInventario/', views.cantidadInventario, name='cantidadInventario_funcion'),
    path('guardarVenta/', views.guardarVenta, name='guardarVenta_funcion'),
    path('etiquetas/', views.etiquetasVista, name='etiquetas_view'),
    path('detallesEtiquetas/<int:ventaId>', views.detallesEtiquetasVista, name='detallesEtiquetas_view'),
]

home/models.py
from django.db import models

# Create your models here.

class articulo(models.Model):
	nombre = models.CharField(max_length=50)
	tipo = models.CharField(max_length=30)
	descripcion = models.CharField(max_length=100)
	fechaCreacion = models.DateTimeField(auto_now_add=True, auto_now=False)

	def __str__(self):
		return self.nombre

class cliente(models.Model):
	nombre = models.CharField(max_length=50)
	descripcion = models.CharField(max_length=100)
	domicilio = models.CharField(max_length=150)
	telefono = models.IntegerField()
	fechaCreacion = models.DateTimeField(auto_now_add=True, auto_now=False)

	def __str__(self):
		return self.nombre

class proveedor(models.Model):
	nombre = models.CharField(max_length=50)
	descripcion = models.CharField(max_length=100)
	domicilio = models.CharField(max_length=150)
	telefono = models.IntegerField()
	fechaCreacion = models.DateTimeField(auto_now_add=True, auto_now=False)

	def __str__(self):
		return self.nombre

class almacen(models.Model):
	nombre = models.CharField(max_length=50)
	descripcion = models.CharField(max_length=100)
	fechaCreacion = models.DateTimeField(auto_now_add=True, auto_now=False)

	def __str__(self):
		return self.nombre

class compra(models.Model):
	articulo = models.ForeignKey('articulo', on_delete=models.CASCADE)
	proveedor = models.ForeignKey('proveedor', on_delete=models.CASCADE)
	almacen = models.ForeignKey('almacen', on_delete=models.CASCADE)
	fechaCreacion = models.DateTimeField(auto_now_add=True, auto_now=False)
	cantidad = models.IntegerField()
	descripcion = models.CharField(max_length=100)

	def __str__(self):
		return self.descripcion

class inventario(models.Model):
	articulo = models.ForeignKey('articulo', on_delete=models.CASCADE)
	almacen = models.ForeignKey('almacen', on_delete=models.CASCADE)
	compra = models.ForeignKey('compra', on_delete=models.CASCADE)
	cantidad = models.IntegerField()

	def __str__(self):
		return str(self.almacen)

class venta(models.Model):
	articulo = models.ForeignKey('articulo', on_delete=models.CASCADE)
	inventario = models.ForeignKey('inventario', on_delete=models.CASCADE)
	cantidad = models.IntegerField()
	cliente = models.ForeignKey('cliente', on_delete=models.CASCADE)
	fechaCreacion = models.DateTimeField(auto_now_add=True, auto_now=False)

	def __str__(self):
		return str(self.id)

home/views.py
from django.shortcuts import render
from django.core.serializers import serialize
from django.views import generic
from .models import articulo, cliente, proveedor, compra, almacen, inventario, venta
from .formularios import registroArticulo, registroCliente, registroProveedor, registroCompra, registroAlmacen, registroInventarioEntrada, registroVenta
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.http import JsonResponse
from django.core.serializers.json import DjangoJSONEncoder

# Create your views here.

class LazyEncoder(DjangoJSONEncoder):
    def default(self, obj):
        if isinstance(obj, json):
            return str(obj)
        return super().default(obj)

def index(request):
	context = {}
	return render(request, "home/index.html", context)

#def articulo(request):
#	context = {}
#	return render(request, "home/articulos.html", context)

class articuloVista(generic.CreateView):
	model = articulo
	form_class = registroArticulo
	template_name = 'home/articulos2.html'
	success_url = reverse_lazy('home_view')

class clienteVista(generic.CreateView):
	model = cliente
	form_class = registroCliente
	template_name = 'home/cliente.html'
	success_url = reverse_lazy('home_view')

class proveedorVista(generic.CreateView):
	model = proveedor
	form_class = registroProveedor
	template_name = 'home/proveedor.html'
	success_url = reverse_lazy('home_view')

class compraVista(generic.CreateView):
	model = compra
	form_class = registroCompra
	template_name = 'home/compra.html'
	success_url = reverse_lazy('home_view')

class almacenVista(generic.CreateView):
	model = almacen
	form_class = registroAlmacen
	template_name = 'home/almacen.html'
	success_url = reverse_lazy('home_view')

def listaArticulosVista(request):
	articulos = articulo.objects.all()
	context = {"listaArticulos":articulos}
	return render(request, "home/listaArticulos.html", context)

def datosArticulo(request, articulo_id):
	articuloObjeto = articulo.objects.filter(id=articulo_id)
	datos = serialize('json', articuloObjeto)
	return HttpResponse(datos)

def cargarAlmacenes(request):
	almacenes = inventario.objects.select_related('almacen').select_related('compra').filter(articulo=request.POST["idArticulo"])
	context = { "form":almacenes }
	return render(request, "home/opcionesAlmacene.html", context)

def compraVistaAlternativa(request):
	formulario = registroCompra(request.POST or None)
	context = {"form" : formulario}
	retorno = "home/compra.html"
	if request.method == "POST":
		if formulario.is_valid():
			retorno = "home/index.html"
			compraGuardar = formulario.save(commit=False)
			compraGuardar.save()
			formularioInv = inventario(articulo=compraGuardar.articulo,almacen=compraGuardar.almacen,compra=compraGuardar,cantidad=compraGuardar.cantidad)
			formularioInv.save()
	return render(request, retorno, context)

def ventaVista(request):
	formulario = registroVenta(request.POST	or None)
	context = {"form":formulario}
	retorno = "home/venta.html"
	if request.method == "POST":
		if formulario.is_valid():
			retorno = "home/index.html"
	return render(request, retorno, context)

class inventarioVista(generic.ListView):
	template_name = "home/inventario.html"
	queryset = inventario.objects.select_related('compra')

def cantidadInventario(request):
	invDatos = inventario.objects.get(id=request.POST["inventarioId"])
	datos = invDatos.cantidad
	return HttpResponse(datos)

def guardarVenta(request):
	ventaGuardar = venta(cantidad=request.POST["cantidad"])
	ventaGuardar.articulo = articulo.objects.get(id=request.POST["articuloId"])
	ventaGuardar.inventario= inventario.objects.get(id=request.POST["inventarioId"])
	ventaGuardar.cliente= cliente.objects.get(id=request.POST["clienteId"])

	datosInventario = inventario.objects.get(id=request.POST["inventarioId"])
	datosInventario.cantidad = datosInventario.cantidad - int(request.POST["cantidad"])

	ventaGuardar.save()
	datosInventario.save()
	return HttpResponse("/")

def etiquetasVista(request):
	ventasObjetos = venta.objects.select_related('cliente').select_related('articulo').select_related('inventario')
	context = {"obj":ventasObjetos}
	return render(request, "home/etiquetas.html", context)

def detallesEtiquetasVista(request, ventaId):
	ventasObjetos = venta.objects.select_related('cliente').select_related('articulo').select_related('inventario').get(id=ventaId)
	almId = ventasObjetos.inventario.almacen.id
	compraId = ventasObjetos.inventario.compra.id
	almacenObjetos = almacen.objects.get(id=almId)
	compraObjetos = compra.objects.get(id=compraId)
	context = {"ventaObj":ventasObjetos, "almacenObj":almacenObjetos, "compraObj":compraObjetos}
	return render(request, "home/detallesEtiqueta.html", context)

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
	<head>
		<script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>

		<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
		
		<link href="{% static 'iconos/css/all.css' %}" rel="stylesheet">

		<link rel="stylesheet" type="text/css" href="{% static 'Css-Propios/global.css' %}">
		<script type="text/javascript" src="{% static 'Script/articulos.js' %}"></script>
		<title>{% block title %}{% endblock %}</title>
	</head>
	<body>
		<nav class="navbar navbar-dark bg-dark navbarLateral" role="navigation">
			<a href="{% url 'articulo_view' %}" class="btn btn-dark">Articulos</a>
			<a href="{% url 'almacenVista_view' %}" class="btn btn-dark">Almacenes</a>
			<a href="{% url 'cliente_view' %}" class="btn btn-dark">Cliente</a>
			<a href="{% url 'proveedor_view' %}" class="btn btn-dark">Proveedor</a>
			<a href="{% url 'compraVista_view' %}" class="btn btn-dark">Compras</a>
			<a href="{% url 'venta_view' %}" class="btn btn-dark">Venta</a>
			<a href="{% url 'inventarioVista_view' %}" class="btn btn-dark">Inventario</a>
			<a href="{% url 'etiquetas_view' %}" class="btn btn-dark">Etiquetas</a>
		</nav>

		<div class="contenido">
			{% block content %}
			
			{% endblock %}
		</div>

		<!-- Modal -->
		<div class="modal fade" id="ventana1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		  <div class="modal-dialog" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <h5 class="modal-title" id="tituloModal">Modal title</h5>
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		          <span aria-hidden="true">&times;</span>
		        </button>
		      </div>
		      <div class="modal-body" id="contenidoModal">
		        
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-secondary" data-dismiss="modal" id="btnCerrarModal">Close</button>
		      </div>
		    </div>
		  </div>
		</div>
	</body>
</html>

templates/home/almacen.html
{% extends "base.html" %}

{% block title %} Etiquetador - Almacen{% endblock %}

{% block content %}

<div class="contenedor-formulario">
	<form method="POST">
<center>
	<h1>Registro de almacen</h1>
</center>
	{% csrf_token %}
	<div class="contenedor-datos">
		<div class="contenedor-controles">
			<label>Nombre</label>
			{{ form.nombre }}
		</div>
		<div class="contenedor-controles">
			<label>Descripcion</label>
			{{ form.descripcion }}
		</div>
	</div>
		<button class="btn btn-success" type="submit">Crear Almacen</button>
	</form>
</div>
 
{% endblock %}

templates/home/articulos.html
{% extends "base.html" %}

{% block title %} Tienda online Registro {% endblock %}

{% block content %}

<div class="contenedor-formulario">
	<form method="POST">
	{% csrf_token %}
	<div class="contenedor-imagen">
		<input type="file" name="imagen" id="inputImg" onchange="cargarImagen(this)" style="display: none;">
		<label for="inputImg">
			<img src="../../static-storage/Imagenes/seleccionaImg.png" id="imagen" class="imagen" name="imagen">
		</label>
	</div>

	<div class="contenedor-datos">
		<div class="contenedor-controles">
			<label>Nombre</label>
			<input type="text" name="nombre" id="txtNombre">
			<button class="btn btn-primary fas fa-search" id="myInput" type="button" data-toggle="modal" data-target="#ventana1" onclick="cargarArticulos()"></button>
		</div>
		<div class="contenedor-controles">
			<label>Fecha</label>
			<input type="date" name="fecha" readonly="true">
		</div>
		<div class="contenedor-controles">
			<label>Tipo</label>
			<select id="cmbTipo" name="tipo">
				<option>Materia prima</option>
				<option>Producto terminado</option>
			</select>
		</div>
		<div class="contenedor-controles">
			<label>Descripcion</label>
			<textarea id="txtDescripcion" name="descripcion"></textarea>
		</div>
	</div>

	<button class="btn btn-success" onclick="guardar()" type="submit">Crear articulo</button>
	</form>
</div>

{% endblock %}

templates/home/articulos2.html
{% extends "base.html" %}

{% block title %} Etiquetador - Articulos{% endblock %}

{% block content %}
<div class="contenedor-formulario">
	<center>
	<h1>Registro de articulo</h1>
</center>
	<form method="POST">
	{% csrf_token %}
		<div class="contenedor-datos">
			<div class="contenedor-controles">
				<label>Nombre</label>
				{{ form.nombre }}
			</div>
			<div class="contenedor-controles">
				<label>Tipo</label>
				{{ form.tipo }}
			</div>
			<div class="contenedor-controles">
				<label>Descripcion</label>
				{{ form.descripcion }}
			</div>
		</div>
		<button class="btn btn-success" type="submit">Crear articulo</button>
	</form>
</div>
 
{% endblock %}

templates/home/compra.html
{% extends "base.html" %}

{% block title %} Etiquetador - Compra{% endblock %}

{% block content %}

<div class="contenedor-formulario">
	<form method="POST">
	{% csrf_token %}
<center>
	<h1>Registro de compra</h1>
</center>
	<div class="contenedor-datos">
		<div class="contenedor-controles">
			<label>Articulo</label>
			{{ form.articulo }}
		</div>
		<div class="contenedor-controles">
			<label>Empresa Proveedora</label>
			{{ form.proveedor }}
		</div>
		<div class="contenedor-controles">
			<label>Cantidad</label>
			{{ form.cantidad }}
		</div>
		<div class="contenedor-controles">
			<label>Almacen de entrada</label>
			{{ form.almacen }}
		</div>
		<div class="contenedor-controles">
			<label>Descripcion</label>
			{{ form.descripcion }}
		</div>
	</div>
		<button class="btn btn-success" type="submit">Crear Compra</button>
	</form>
</div>

{% endblock %}

templates/home/detallesEtiqueta.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %} Etiquetador - Etiquetas{% endblock %}

{% block content %}

<center>
	<h1>Detalles de la etiqueta {{ ventaObj.id }}-{{ ventaObj.inventario.id }}-{{ ventaObj.cliente.id }}</h1>
</center>
<div class="container">
	<div class="row">
		<div class="col">
			<h1>Datos de venta</h1>
			<table class="table table-hover table-dark">
				<thead><tr>
					<th>#</th>
					<th>Cantidad</th>
					<th>Fecha de venta</th>
				</tr></thead>
				<tbody><tr>
					<td>{{ ventaObj.id }}</td>
					<td>{{ ventaObj.cantidad }}</td>
					<td>{{ ventaObj.fechaCreacion }}</td>
				</tr></tbody>
			</table>
		</div>
		<div class="col">
			<h1>Datos de Almacen</h1>
			<table class="table table-hover table-dark">
				<thead><tr>
					<th>#</th>
					<th>Nombre</th>
				</tr></thead>
				<tbody><tr>
					<td>{{ almacenObj.id }}</td>
					<td>{{ almacenObj.nombre }}</td>
				</tr></tbody>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="col">
			<h1>Datos Cliente</h1>
			<table class="table table-hover table-dark">
				<thead><tr>
					<th>#</th>
					<th>Nombre</th>
					<th>Descripcion</th>
				</tr></thead>
				<tbody><tr>
					<td>{{ ventaObj.cliente.id }}</td>
					<td>{{ ventaObj.cliente.nombre }}</td>
					<td>{{ ventaObj.cliente.descripcion }}</td>
				</tr></tbody>
			</table>
		</div>
		<div class="col">
			<h1>Datos Proveedor</h1>
			<table class="table table-hover table-dark">
				<thead><tr>
					<th>#</th>
					<th>Nombre</th>
					<th>Descripcion</th>
				</tr></thead>
				<tbody><tr>
					<td>{{ compraObj.proveedor.id }}</td>
					<td>{{ compraObj.proveedor.nombre }}</td>
					<td>{{ compraObj.proveedor.descripcion }}</td>
				</tr></tbody>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="col">
			<h1>Datos del Articulo</h1>
			<table class="table table-hover table-dark">
				<thead><tr>
					<th>#</th>
					<th>Nombre</th>
					<th>Descripcion</th>
				</tr></thead>
				<tbody><tr>
					<td>{{ ventaObj.articulo.id }}</td>
					<td>{{ ventaObj.articulo.nombre }}</td>
					<td>{{ ventaObj.articulo.descripcion }}</td>
				</tr></tbody>
			</table>
		</div>
		<div class="col">
			<h1>Datos de Compra</h1>
			<table class="table table-hover table-dark">
				<thead><tr>
					<th>#</th>
					<th>Cantidad</th>
					<th>Descripcion</th>
					<th>Fecha de compra</th>
				</tr></thead>
				<tbody><tr>
					<td>{{ compraObj.id }}</td>
					<td>{{ compraObj.cantidad }}</td>
					<td>{{ compraObj.descripcion }}</td>
					<td>{{ compraObj.fechaCreacion }}</td>
				</tr></tbody>
			</table>
		</div>
	</div>
</div>

{% endblock %}

templates/home/etiquetas.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %} Etiquetador - Etiquetas{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col">
			<center>
				<h1>Etiquetas</h1>
			</center>
			<table class="table table-hover table-dark">
				<thead>
					<tr>
						<th>Etiquetas</th>
					</tr>
				</thead>
				<tbody>
					{% for venta in obj %}
					<tr>
						<td><a href="{% url 'detallesEtiquetas_view' venta.id %}">{{ venta.id }}-{{ venta.inventario.id }}-{{ venta.cliente.id }}</a></td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
<div>
{% endblock %}

templates/home/index.html
{% extends "base.html" %}

{% block title %} Tienda online {% endblock %}

{% block content %}

<div class="contenedor-principal">
	<h1 style="text-align:center;">Bienvenidos</h1>
</div>

{% endblock %}

templates/home/inicioSesion.html
{% extends "base.html" %}

{% block title %} Tienda online Registro {% endblock %}

{% block content %}

<div class="contenedor-logo">
	<i class="logo"></i>
</div>

<div class="contenedor-central">
	<div>
		<h1>Iniciar secion</h1>
	</div>
	<form>
		<div class="contendor-input">
			<label>Correo Electronico</label>
			<input type="text" name="">
		</div>
		<div class="contendor-input">
			<label>Contrasena</label>
			<input type="password" name="">
		</div>
		<div class="contendor-input">
			<button class="btn btn-success">Iniciar secion</button>
		</div>	
	</form>
</div>

{% endblock %}

templates/home/inventario.html
{% extends "base.html" %}

{% block title %} Etiquetador - Articulos{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col">
			<center>
	<h1>Lista de Inventario</h1>
</center>
			<table class="table table-hover table-dark">
				<thead>
					<thead>
						<tr>
							<td>#</td>
							<td>Articulo</td>
							<td>Almacen</td>
							<td>Cantidad</td>
							<td>Proveedor</td>
							<td>Fecha de compra</td>
						</tr>
					</thead>
				</thead>
				<tbody>
					{% for inv in object_list %}
					<tr>
						<td>{{ inv.id }}</td>
						<td>{{ inv.articulo }}</td>
						<td>{{ inv.almacen }}</td>
						<td>{{ inv.cantidad }}</td>
						<td>{{ inv.compra.proveedor }}</td>
						<td>{{ inv.compra.fechaCreacion }}</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
 
{% endblock %}

templates/home/listaArticulos.html
<table class="table table-hover table-dark">
	<tbody>
		<thead>
			<tr>
				<th>#</th>
				<th>Nombre</th>
				<th>--</th>
			</tr>
		</thead>
		{% for articulo in listaArticulos %}
		<tr>
			<td>{{ articulo.id }}</td>
			<td>{{ articulo.nombre }}</td>
			<td onclick="colocarDatos(this)"><span class="fa fa-arrow-right"></span></td>
		</tr>
		{% endfor %}
	</tbody>
</table>

templates/home/opcionesAlmacene.html
<table class="table table-hover table-dark">
	<tbody>
		<thead>
			<tr>
				<th>#</th>
				<th>Nombre</th>
				<th>Proveedor</th>
				<th>Compra</th>
				<th>Cantidad</th>
				<th>--</th>
			</tr>
		</thead>
		{% for inv in form %}
		<tr>
			<td>{{ inv.id }}</td>
			<td>{{ inv.almacen.nombre }}</td>
			<td>{{ inv.compra.proveedor }}</td>
			<td>{{ inv.compra.id }}</td>
			<td>{{ inv.cantidad }}</td>
			<td onclick="colocarDatosInv(this)"><span class="fa fa-arrow-right"></span></td>
		</tr>
		{% endfor %}
	</tbody>
</table>

templates/home/registroUsuario.html
{% extends "base.html" %}

{% block title %} Tienda online Registro {% endblock %}

{% block content %}

<div class="contenedor-logo">
	<i class="logo"></i>
</div>

<div class="contenedor-central">
	<div>
		<h1>Crea tu Cuenta</h1>
	</div>
	<form>
		<div class="contendor-input">
			<label>Tu nombre</label>
			<input type="text" name="">
		</div>
		<div class="contendor-input">
			<label>Correo Electronico</label>
			<input type="text" name="">
		</div>
		<div class="contendor-input">
			<label>Contrasena</label>
			<input type="password" name="">
		</div>
		<div class="contendor-input">
			<button class="btn btn-success">Crear tu cuenta</button>
		</div>	
	</form>
	<div class="contendor-input">
		<a href="{% url 'inicioSecion_view' %}">Inicia secion</a>
	</div>
</div>

{% endblock %}

templates/home/usuario.html
{% extends "base.html" %}

{% block title %} Tienda online Registro {% endblock %}

{% block content %}

<div class="contenedor-cabecero">
	<div class="baner">
		<input type="file" name="" onchange="establecerImg(this)">
		<i src=""></i>
	</div>
	<div class="baner-menu">
		<div class="contenedor-botones">
			<ul>
				<li>
					<button class="btn btn-primary">Mensaje</button>
				</li>
				<li>
					<button class="btn btn-success">Seguir</button>
				</li>
				<li>
					<button class="btn btn-danger">Reportar</button>
				</li>
			</ul>
		</div>
	</div>
	<div class="contenedor-imagen-principal">
		<div class="contenedor-imagen">
			
		</div>
	</div>
	<div style="height: 50000px;">
		
	</div>
</div>

{% endblock %}

templates/home/venta.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %} Etiquetador - Venta{% endblock %}

{% block content %}

<div class="contenedor-formulario">
	<form method="POST">
<center>
	<h1>Registro de venta</h1>
</center>
	{% csrf_token %}
	<div class="contenedor-datos">
		<div class="contenedor-controles">
			<label>Articulo</label>
			<input type="text" name="articulo" id="id_articulo" readonly="true">
			<button class="btn btn-primary" type="button" data-toggle="modal" data-target="#ventana1" onclick="listaArticulos()">Buscar</button>
		</div>
		<div class="contenedor-controles">
			<label>Almacen</label>
			<input type="text" name="inventario" id="id_inventario" readonly="true">
			<button class="btn btn-primary" type="button" data-toggle="modal" data-target="#ventana1" onclick="cargarAlmacenes()">Buscar</button>
		</div>
		<div class="contenedor-controles">
			<label>Cantidad disponible</label>
			<input type="text" id="id_cantidadDisponible" readonly="true" value="0">
		</div>
		<div class="contenedor-controles">
			<label>Cantidad Venta</label>
			<input type="text" name="cantidad" id="id_cantidad" onkeypress="return soloNumeros(event)">
		</div>
		<div class="contenedor-controles">
			<label>Cliente</label>
			{{ form.cliente }}
		</div>
	</div>
		<button class="btn btn-success" type="button" onclick="guardarVenta()">Crear Venta</button>
	</form>
</div>
<script type="text/javascript" src="{% static 'Script/venta.js' %}"></script>
<script type="text/javascript">var tokenSeguridad = '{{ csrf_token }}';</script>

{% endblock %}